# Offer the fix lint bot command
offerLintFix:
  # Which job name to look for
  jobName: lint
  # Define which linter outputs should be checked for auto-fixability
  linters:
    - eslint
    - wotan
    - prettier

# Check whether the resulting squash-commit will be semantic
semanticSquash: true

# Configure closing stale issues
stale:
  # Which job name to look for
  jobName: stale
  # Which labels mark an issue as closeable
  labels:
    - 'cannot fix ❌'
    - 'duplicate'
    - 'external'
    - 'wontfix'
    - 'working as intended ✔'
    - 'waiting for info ⏳'
  # How long issues with these labels may stay open
  afterDays: 5
  # What to comment when an issue gets closed
  comment: |
    This issue has not seen any recent activity and was marked as "${label}".
    Closing for housekeeping purposes... 🧹

    Feel free to reopen if the issue persists.

# Configure auto-labeling
autoLabel:
  # Add one array entry for each rule
  - pattern: 'packages\/config\/config\/(.*\/)?.+\.json|\.gitignore' # Regex to match filenames
    only: true # Whether non-matching files should be allowed
    remove: false # Whether to remove the label if the rule no longer applies
    label: 'config ⚙' # Which label to add/remove
