name: Generate documentation

# Run this workflow on all pushes to master and pull requests
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  # This job checks if the docs can be generated and produce changes
  # If they do, a PR will be created with the changes
  check-and-update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    outputs:
      CHANGES: ${{ steps.changes.outputs.CHANGES }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # We need npm@7 for the workspaces feature
    - name: Update npm to >=7
      run: "[ $(npm -v | cut -d. -f1) -lt 7 ] && npm i -g npm@7"

    - name: Install dependencies
      run: npm ci

    - name: Compile TypeScript code
      run: npm run build

    - name: Test documentation generation
      run: npm run docs:generate

    - name: Check for changes
      id: changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "::set-output name=CHANGES::true"
        fi

    # Trigger this step only when pushing to master and changes were detected
    - name: Create or update PR
      if: |
        steps.changes.outputs.CHANGES == 'true' && 
        github.event_name == 'push' && 
        github.ref == 'refs/heads/master'
      uses: ./.github/actions/generateTypedDocs
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
      env:
        CI: true
