name: 'Z-Wave Bot: Scheduled actions'

on:
  schedule:
    # every 15 minutes
    - cron:  '*/15 * * * *'

jobs:
  stale:
    runs-on: [ubuntu-latest]
    steps:
      - name: Trigger Stale App
        run: echo "Trigger Stale App!"
